version: '2.3'

services:
  shimao:
    container_name: shimao-pytorch
    image: mshimao/pytorch-latest
    build: ../../Dockerfiles/pytorch
    runtime: nvidia
    ipc: host
    ports:
      - 'port-to-tensorboard:6006'
      - 'port-to-jupyternotebook:8888'
    volumes:
      - /path-to-volume:/root/volume
      - /path-to-data:/data
    command: /usr/local/bin/jupyter-notebook --allow-root --ip="0.0.0.0"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - label:disable
